name: Bug Report
description: Reportar um erro ou comportamento inesperado.
title: "[BUG] "
labels: ["bug", "triage"]
type: Bug
projects: ["octo-org/1"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um erro! Preencha as informações abaixo para que possamos reproduzir e resolver o problema.
  - type: input
    id: tenant
    attributes:
      label: Ambiente (Tenant)
      placeholder: ex. empresa-x, staging, prod-br
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versão
      placeholder: ex. 3.2.0 20250623
    validations:
      required: true
  - type: dropdown
    id: tier
    attributes:
      label: Tier
      options:
        - local
        - tiny
        - small
        - medium
        - large
      default: 2
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: O que aconteceu?
      description: O que você esperava que acontecesse? O que aconteceu de fato?
      placeholder: O botão “Salvar” não funcionou após preencher o formulário.
    validations:
      required: true
  - type: textarea
    id: passos
    attributes:
      label: Passos para reproduzir
      placeholder: |
        1. Acesse Configurações
        2. Clique em “Salvar”
        3. Observe o erro
  - type: checkboxes
    id: navegador
    attributes:
      label: Navegador
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Outro (especificar abaixo)
  - type: input
    id: versao_navegador
    attributes:
      label: Versão do navegador (se aplicável)
      placeholder: ex. Chrome 125.0.6422.141
  - type: textarea
    id: logs
    attributes:
      label: Logs ou mensagens relevantes
      render: shell
